# Generated by Django 3.2.5 on 2021-07-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason_for_appointment',
            field=models.TextField(max_length=256, null=True),
        ),
    ]
