# Generated by Django 3.2.5 on 2021-07-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_otp_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ph_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
